# Generated by Django 4.2 on 2023-04-11 05:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('dob', models.DateField()),
                ('doj', models.DateField()),
                ('department', models.CharField(max_length=100)),
                ('post', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=100)),
                ('country', models.CharField(max_length=100)),
                ('zipCode', models.IntegerField()),
                ('state', models.CharField(max_length=100)),
                ('active', models.BooleanField(default=True)),
                ('leaveCount', models.IntegerField(default=0)),
                ('on_leave', models.BooleanField(default=True)),
            ],
        ),
    ]
